# mkdocs.yml
site_name: AWS Infrastructure Documentation

theme:
  name: material
  palette:
    primary: deep-purple
    accent: deep-purple
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - header.autohide

nav:
  - Home: index.md
  - OnBoarding: onboarding/index.md
  - Infrastructure:
      - Overview: infrastructure/index.md
      - VPC Configuration: infrastructure/vpc-cloud.md
  - Provision & Build: provision/index.md
  - Connect & Test: connect/index.md
  - Integration: integration/index.md
  - Operating Guide: operations/index.md
  - Changelog: changelog.md
  - Projects: projects.md

plugins:
  - search
