site_name: AWS Infrastructure Documentation

theme:
  name: material
  palette:
    primary: deep-purple
    accent: deep-purple
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.tabs.link
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - OnBoarding: onboarding/index.md
  - Infrastructure:
      - Overview: infrastructure/index.md
      - VPC Configuration: infrastructure/vpc-cloud.md
  - Provision & Build: provision/index.md
  - Connect & Test: connect/index.md
  - Integration: integration/index.md
  - Operating Guide: operations/index.md
  - Changelog: changelog.md
  - Projects: projects.md
